Set up CI with Azure Pipelines
[skip ci]

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,122 +1,17 @@
 trigger:
   - sampleCode
+
 pool:
   vmImage: ubuntu-latest
+
+variables:
+  - group: TestResults
+
 steps:
-  - task: NodeTool@0
-    inputs:
-      versionSpec: '16.x'
-    displayName: 'Install Node.js'
   - task: UsePythonVersion@0
     inputs:
-      versionSpec: '3.10.13'
+      versionSpec: '3.9'
     displayName: 'Setup Python'
-
-  - script: |
-      cd samples/java/testng
-      mvn clean compile test
-    displayName: 'Run Selenium TestNG Tests'
-    continueOnError: true
-
-  - script: |
-      cd samples/java/testng
-      pip install trcli
-      trcli -y \
-        -h "https://INSTANCE-NAME.testrail.io" \
-        --project "AzurePipelinesExamples" \
-        -u "USERNAME" \
-        -p "PASSWORD" \
-        parse_junit \
-        -f "reports/TEST-TestSuite.xml" \
-        --title "Selenium TestNG Automated Tests Executed From AzureDevOps Pipelines" \
-        --run-description "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
-    displayName: 'Upload Selenium TestNG Results in TestRail With TestRail CLI'
-
-  - script: |
-      cd samples/java/junit5
-      mvn clean compile test
-    displayName: 'Run Selenium Junit5 Tests'
-    continueOnError: true
-
-  - script: |
-      cd samples/java/junit5
-      pip install trcli
-      trcli -y \
-        -h "https://INSTANCE-NAME.testrail.io" \
-        --project "AzurePipelinesExamples" \
-        -u "USERNAME" \
-        -p "PASSWORD" \
-        parse_junit \
-        -f "target/TEST-junit-jupiter.xml" \
-        --title "Selenium Junit5 Automated Tests Executed From AzureDevOps Pipelines" \
-        --run-description "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
-    displayName: 'Upload Selenium Junit5 Test Results in TestRail With TestRail CLI'
-
-  - script: |
-      cd samples/javascript/playwright
-      npm install
-      npx playwright install-deps
-      npx playwright install
-      npx playwright test
-    displayName: 'Run Playwright tests'
-    continueOnError: true
-
-  - script: |
-      cd samples/javascript/playwright
-      pip install trcli
-      trcli -y \
-        -h "https://INSTANCE-NAME.testrail.io" \
-        --project "AzurePipelinesExamples" \
-        -u "USERNAME" \
-        -p "PASSWORD" \
-        parse_junit \
-        -f "test-results/junit-report.xml" \
-        --title "Playwright automated tests" \
-        --run-description "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
-    displayName: 'Upload Playwright Test Results in TestRail with TestRail CLI'
-
-  - script: |
-      cd samples/robotframework/robotframework-browser
-      pip install robotframework-browser
-      rfbrowser init
-      robot -d reports -x junit-report.xml "./tests" || true
-    displayName: 'Run Robot Framework tests'
-    continueOnError: true
-
-  - script: |
-      cd samples/robotframework/robotframework-browser
-      pip install trcli
-      trcli -y \
-        -h "https://INSTANCE-NAME.testrail.io" \
-        --project "AzurePipelinesExamples" \
-        -u "USERNAME" \
-        -p "PASSWORD" \
-        parse_junit \
-        -f "reports/junit-report.xml" \
-        --title "RobotFramework Automated Tests Executed From AzureDevOps Pipelines" \
-        --run-description "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
-    displayName: 'Upload Robot Framework tets results with TestRail CLI'
-
-  - script: |
-      cd samples/javascript/cypress
-      npm install
-      npx cypress run --reporter junit --reporter-options mochaFile=reports/junit-[hash].xml
-    displayName: 'Run Cypress Tests'
-    continueOnError: true
-
-  - script: |
-      cd samples/javascript/cypress
-      pip install trcli
-      trcli -y \
-        -h "https://INSTANCE-NAME.testrail.io" \
-        --project "AzurePipelinesExamples" \
-        -u "USERNAME" \
-        -p "PASSWORD" \
-        parse_junit \
-        -f "reports/junit*.xml" \
-        --title "Cypress Automated Tests Executed From AzureDevOps Pipelines" \
-        --run-description "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
-    displayName: 'Upload Cypress Test Results With TestRail CLI'
 
   - script: |
       cd samples/python/pytest
@@ -126,15 +21,26 @@ steps:
     continueOnError: true
 
   - script: |
-      cd samples/python/pytest
-      pip install trcli
-      trcli -y \
-        -h "https://INSTANCE-NAME.testrail.io" \
-        --project "AzurePipelinesExamples" \
-        -u "USERNAME" \
-        -p "PASSWORD" \
-        parse_junit \
-        -f "reports/junit-report.xml" \
-        --title "Pytest Automated Tests Executed From AzureDevOps Pipelines" \
-        --run-description "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
-    displayName: 'Upload Pytest Results in TestRail With TestRail CLI'
+      echo "Current working directory:"
+      pwd
+      echo "Listing files in the reports directory:"
+      ls -l reports/ || echo "Reports directory not found"
+      echo "API_URL is $API_URL"
+      echo "API_KEY is $API_KEY"
+      echo "Checking if JUnit report file exists at $JUNIT_FILE_PATH"
+      if [ -f "$JUNIT_FILE_PATH" ]; then
+        echo "JUnit report file found: $JUNIT_FILE_PATH"
+        CURL_COMMAND="curl -X POST $API_URL -H \"x-api-key: $API_KEY\" -F \"file=@$JUNIT_FILE_PATH\""
+        echo "Executing curl command: $CURL_COMMAND"
+        RESPONSE=$(eval $CURL_COMMAND)
+        echo "API Response:"
+        echo "$RESPONSE"
+      else
+        echo "JUnit report file not found: $JUNIT_FILE_PATH"
+        exit 1
+      fi
+    displayName: 'Upload Pytest Results to Backend'
+    env:
+      JUNIT_FILE_PATH: "samples/python/pytest/reports/junit-report.xml"
+      API_URL: $(API_URL)
+      API_KEY: $(API_KEY)
