Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,263 +1,78 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/2.0/configuration-reference
 version: 2.1
-orbs:
-  browser-tools: circleci/browser-tools@1.4.1
-working_directory: ~/automation-framework-integration
-jobs:
-  build-and-test-playwright-tests:
-    docker:
-      - image: cimg/node:21.2.0
-    steps:
-      - checkout
-      - run:
-          name: run the Playwright tests
-          command: |
-            cd samples/javascript/playwright
-            npm install
-            npx playwright install-deps
-            npx playwright install
-            npx playwright test || true
-      - persist_to_workspace:
-          root: ./
-          paths:
-            - samples/javascript/playwright/test-results/junit-report.xml
-  install-trcli-and-parse-results-playwright:
-    docker:
-      - image: cimg/python:3.11
-    steps:
-      - attach_workspace:
-          at: ./automation-framework-integration
-      - run:
-          name: Install TR CLI and upload the test results to TestRail
-          command: |
-            pip install trcli
-            trcli -y \
-            -h $TESTRAIL_INSTANCE_URL \
-            --project "Examples CircleCI" \
-            -u $TESTRAIL_USERNAME \
-            -p $TESTRAIL_PASSWORD \
-            parse_junit \
-            --title "Automated Playright Tests from CircleCI Workflow" \
-            --run-description $CIRCLE_BUILD_URL \
-            -f "./automation-framework-integration/samples/javascript/playwright/test-results/junit-report.xml"
 
-  build-and-test-python-tests:
+jobs:
+  checkout:
     docker:
-      - image: cimg/python:3.12.0-browsers
+      - image: circleci/python:3.10
+    steps:
+      - checkout
+
+  setup-venv:
+    docker:
+      - image: circleci/python:3.10
     steps:
       - checkout
       - run:
-          name: run pytest tests
+          name: Setup virtual environment
           command: |
             cd samples/python/pytest
-            pip install -r requirements.txt || true
-            pytest --junitxml "reports/junit-report.xml" "./tests" || true
-      - persist_to_workspace:
-          root: ./
-          paths:
-            - samples/python/pytest/reports
-  install-trcli-and-parse-results-python:
-    docker:
-      - image: cimg/python:3.11
-    steps:
-      - attach_workspace:
-          at: ./automation-framework-integration
-      - run:
-          name: Install TR CLI and upload the Python test results to TestRail
-          command: |
-            pip install trcli
-            trcli -y \
-            -h $TESTRAIL_INSTANCE_URL \
-            --project "Examples CircleCI" \
-            -u $TESTRAIL_USERNAME \
-            -p $TESTRAIL_PASSWORD \
-            parse_junit \
-            --title "Automated Python Tests from CircleCI Workflow" \
-            --run-description $CIRCLE_BUILD_URL \
-            -f "./automation-framework-integration/samples/python/pytest/reports/junit-report.xml"
+            python -m venv ./venv
 
-  build-and-test-robotframework-tests:
+  execute-tests:
     docker:
-      - image: cimg/python:3.7-browsers
+      - image: circleci/python:3.10
     steps:
       - checkout
       - run:
-          name: run robot framework tests
+          name: Execute automated tests
           command: |
-            cd samples/robotframework/robotframework-browser
-            node -v
-            python --version
-            node --version
-            java --version
-            google-chrome --version
-            pip install -r requirements.txt && \
-            rfbrowser init && \
-            robot -d reports -x junit-report.xml "./tests" || true
-      - persist_to_workspace:
-          root: ./
-          paths:
-            - samples/robotframework/robotframework-browser/reports
-  install-trcli-and-parse-results-robotframework:
-    docker:
-      - image: cimg/python:3.11
-    steps:
-      - attach_workspace:
-          at: ./automation-framework-integration
-      - run:
-          name: Install TR CLI and upload the test results to TestRail
-          command: |
-            pip install trcli
-            trcli -y \
-            -h $TESTRAIL_INSTANCE_URL \
-            --project "Examples CircleCI" \
-            -u $TESTRAIL_USERNAME \
-            -p $TESTRAIL_PASSWORD \
-            parse_junit \
-            --title "Automated RobotFramework Tests from CircleCI Workflow" \
-            --run-description $CIRCLE_BUILD_URL \
-            -f "./automation-framework-integration/samples/robotframework/robotframework-browser/reports/junit-report.xml"
+            cd samples/python/pytest
+            . ./venv/bin/activate
+            pip install -r requirements.txt
+            pytest --junitxml=reports/junit-report.xml ./tests || true
+            echo "JUnit report generated:"
+            ls -l reports/
 
-  build-and-test-cypress-tests:
+  post-results:
     docker:
-      - image: cypress/base:latest
+      - image: circleci/python:3.10
+    environment:
+      API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6IjE2ODdiMTE1LWE0MzItNDQyZC1iYzAwLWQ4MzU5Mzk1NzAyOSIsInVzZXJJZCI6ImNlZTA5ZDQyLTA2YzMtNDU5OS1hODZlLTg2YzgwMTM4ZGNiOSIsImlhdCI6MTcyMTEyNjA3OH0.tRsXbvHXgXSlnRGCSiS_pDvxS5BrqH_i_WCpV4GCgaI"
+      API_URL: "http://localhost:3000/api/projects/integration/jenkins/result/beeeb35d-1633-4ac1-a16c-a459a2d7b302"
     steps:
       - checkout
       - run:
-          name: run the Cypress tests
+          name: Post results
           command: |
-            cd samples/javascript/cypress
-            npm install
-            npx cypress run --reporter junit --reporter-options "mochaFile=reports/junit-[hash].xml" || true
-      - persist_to_workspace:
-          root: ./
-          paths:
-            - samples/javascript/cypress/reports
-  install-trcli-and-parse-results-cypress:
-    docker:
-      - image: cimg/python:3.11
-    steps:
-      - attach_workspace:
-          at: ./automation-framework-integration
-      - run:
-          name: Install TR CLI and upload the test results to Testrail
-          command: |
-            pip install trcli
-            trcli -y \
-            -h $TESTRAIL_INSTANCE_URL \
-            --project "Examples CircleCI" \
-            -u $TESTRAIL_USERNAME \
-            -p $TESTRAIL_PASSWORD \
-            parse_junit \
-            --title "Automated Playright Tests from CircleCI workflow" \
-            --run-description $CIRCLE_BUILD_URL \
-            -f "./automation-framework-integration/samples/javascript/cypress/reports/junit*.xml"
+            cd samples/python/pytest
+            junitFilePath="reports/junit-report.xml"
+            
+            if [ -f "${junitFilePath}" ]; then
+                echo "JUnit report file found: ${junitFilePath}"
+                
+                response=$(curl -X POST ${API_URL} \
+                  -H "x-api-key: ${API_KEY}" \
+                  -F "file=@${junitFilePath}")
 
-  build-and-test-testng-selenium:
-    docker:
-      - image: cimg/openjdk:15.0-browsers
-    steps:
-      - browser-tools/install-browser-tools:
-          chrome-version: 109.0.5414.74
-      # Checkout the code as the first step.
-      - checkout
-      # Build and run the tests
-      - run:
-          name: Build and run the TestNG Selenium
-          command: |
-            cd samples/java/testng-selenium
-            mvn clean compile test || true
-      - persist_to_workspace:
-          root: ./
-          paths:
-            - samples/java/testng-selenium/reports
-  install-trcli-and-parse-results-testng-selenium:
-    docker:
-      - image: cimg/python:3.11
-    steps:
-      - attach_workspace:
-          at: ./automation-framework-integration
-      - run:
-          name: Install TR CLI and upload the test results to TestRail
-          command: |
-            pip install trcli
-            trcli -y \
-             -h $TESTRAIL_INSTANCE_URL \
-             --project "Examples CircleCI" \
-             -u $TESTRAIL_USERNAME \
-             -p $TESTRAIL_PASSWORD \
-             parse_junit \
-             --title "Automated TestNG Selenium Tests from CircleCI Workflow" \
-             --run-description $CIRCLE_BUILD_URL \
-             -f "./automation-framework-integration/samples/java/testng-selenium/reports/TEST-TestSuite.xml"
+                echo "API Response:"
+                echo "${response}"
+                
+            else
+                echo "JUnit report file not found: ${junitFilePath}"
+                exit 1
+            fi
 
-  build-and-test-junit-selenium:
-    docker:
-      - image: cimg/openjdk:15.0
-    steps:
-      - browser-tools/install-browser-tools:
-          chrome-version: 109.0.5414.74
-      # Checkout the code as the first step.
-      - checkout
-      # Build and run the tests
-      - run:
-          name: Build and run the Junit Selenium tests
-          command: |
-            cd samples/java/junit5-selenium
-            mvn clean compile test
-      - persist_to_workspace:
-          root: ./
-          paths:
-            - samples/java/junit5-selenium/target/TEST-junit-jupiter.xml
-  install-trcli-and-parse-results-junit-selenium:
-    docker:
-      - image: cimg/python:3.11
-    steps:
-      - attach_workspace:
-          at: ./automation-framework-integration
-      - run:
-          name: Install TR CLI and upload the test results to TestRail
-          command: |
-            pip install trcli
-            trcli -y \
-             -h $TESTRAIL_INSTANCE_URL \
-             --project "Examples CircleCI" \
-             -u $TESTRAIL_USERNAME \
-             -p $TESTRAIL_PASSWORD \
-             parse_junit \
-             --title "Automated JUnit Selenium Tests from CircleCI Workflow" \
-             --run-description $CIRCLE_BUILD_URL \
-             -f "./automation-framework-integration/samples/java/junit5-selenium/target/TEST-junit-jupiter.xml"
-# Invoke jobs via workflows
 workflows:
-  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
+  version: 2
+  sample:
     jobs:
-      - build-and-test-playwright-tests
-      - install-trcli-and-parse-results-playwright:
+      - checkout
+      - setup-venv:
           requires:
-            - build-and-test-playwright-tests
-
-      - build-and-test-testng-selenium
-      - install-trcli-and-parse-results-testng-selenium:
+            - checkout
+      - execute-tests:
           requires:
-            - build-and-test-testng-selenium
-
-      - build-and-test-python-tests
-      - install-trcli-and-parse-results-python:
+            - setup-venv
+      - post-results:
           requires:
-            - build-and-test-python-tests
-
-      - build-and-test-robotframework-tests
-      - install-trcli-and-parse-results-robotframework:
-          requires:
-            - build-and-test-robotframework-tests
-
-      - build-and-test-cypress-tests
-      - install-trcli-and-parse-results-cypress:
-          requires:
-            - build-and-test-cypress-tests
-
-      - build-and-test-junit-selenium
-      - install-trcli-and-parse-results-junit-selenium:
-          requires:
-            - build-and-test-junit-selenium
+            - execute-tests
